### ISSUE TITLE
Suggestion for base64 decode

### ISSUE THREAD

**Issue by geripgeri** [JoergM/consul-examples#1]
Just a friendly suggestion: you can use `base64 --decode` to decode the payload:

[README.md](https://github.com/JoergM/consul-examples/blob/master/events_watches_locks/README.md):
> The Payload is Base64 encoded. Your program would have to decode it (which cat does not :) ) The Base64 encoding allows to send binary payload as well.

**Comment by JoergM** [comment]
Thanks. You can indeed. The explanation was a bit misleading. The comment in parenthesis referenced the following command: 

```
consul watch -type event -name exampleEvent cat
```

The cat at the end simply outputs the resulting JSON. You could put whatever command there and interpret the JSON. If that happens to be a shell script it can of course use base64 to decode the content of the field "Payload" 

It would not make sense to just replace the 'cat' by 'base64 --decode' as only one field of the JSON is base64 encoded.

I changed the text to make it less misleading.

**Comment by geripgeri** [comment]
Sorry for misunderstanding, I only thought you can show a little tip in the readme like this:

> 
> The content of the field 'Payload' is Base64 encoded. Your program would have to decode it. 
> For example: `base64 --decode`
>The Base64 encoding allows to send binary payload as well.

**Comment by JoergM** [comment]
Good point. I added 'base64 --decode' as example.

**Comment by geripgeri** [comment]
Thanks 👍
